  services:
    mysql:
      image: mysql
      ports:
        - "3306:3306"
      expose:
        - "3306"
      environment:
        - MYSQL_DATABASE=${DB_NAME}
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      volumes:
        - "./conf.d:/etc/mysql/conf.d:ro"